# Generated by Django 4.1.2 on 2022-10-16 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=5000, null=True)),
                ('image', models.CharField(blank=True, max_length=5000, null=True)),
                ('email_from', models.CharField(blank=True, max_length=5000, null=True)),
                ('emails_destiny', models.TextField()),
                ('color', models.CharField(blank=True, max_length=5000, null=True)),
                ('body', models.CharField(blank=True, max_length=5000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
            },
        ),
    ]
