# Generated by Django 4.1.2 on 2022-10-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='body',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='color',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='email_from',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Email de envio'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='emails_destiny',
            field=models.TextField(verbose_name='Emails de destino'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Link da imagem'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Cabeçalho'),
        ),
    ]
