# Generated by Django 4.1.2 on 2022-10-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_body_alter_campaign_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem'),
        ),
    ]
