# Generated by Django 4.1.2 on 2022-10-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='color',
            field=models.CharField(blank=True, choices=[('Vermelho', 'vermelho'), ('Azul', 'azul'), ('Verde', 'verde')], max_length=5000, null=True, verbose_name='Cor'),
        ),
    ]
