# Generated by Django 4.1.2 on 2022-10-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_campaign_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='emails_destiny',
            field=models.TextField(verbose_name='Informe os emails de destino separado por vírgula'),
        ),
    ]
