# Generated by Django 4.1.2 on 2022-10-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_campaign_emails_destiny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='color',
            field=models.CharField(blank=True, choices=[('vermelho', 'Vermelho'), ('azul', 'Azul'), ('verde', 'Verde')], max_length=5000, null=True, verbose_name='Cor'),
        ),
    ]
