# Generated by Django 4.1.2 on 2022-10-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_alter_campaign_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='color',
            field=models.CharField(blank=True, choices=[('vermelho', 'vermelho'), ('azul', 'azul'), ('verde', 'verde')], max_length=5000, null=True, verbose_name='Cor'),
        ),
    ]
