# Generated by Django 4.0.8 on 2022-10-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_alter_campaign_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='color',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Informe a cor. A cor só podem ser = azul ou verde ou vermelho, informe em texto e tudo minusculo sem espaço'),
        ),
    ]
